### ISSUE TITLE
PHP 8.1 compatibility

### ISSUE THREAD

**Issue by Jan-E** [php/pecl-networking-xmlrpc#1]
Quote from https://github.com/php/php-src/blob/fc56de113ca98a4c820eca5536f1c3e839d041ef/UPGRADING.INTERNALS#L52-L54
> f. Non-serializable classes should be indicated using the
>      ZEND_ACC_NOT_SERIALIZABLE (@not-serializable in stubs) rather than the
>      zend_class_(un)serialize_deny handlers which are removed.

This has to be adjusted in https://github.com/php/pecl-networking-xmlrpc/blob/e5c4bb3ce4e0b9933f655a9c5eebfbfd9064660e/xmlrpc-epi-php.c#L232-L233

**Comment by Jan-E** [comment]
Wow. That is fast.

**Comment by mlocati** [comment]
Any ETA for a new release on https://pecl.php.net/package/xmlrpc ?

**Comment by remicollet** [comment]
IMHO, no urgency until 8.1 API is final (so for RC)

**Comment by cmb69** [comment]
Nobody should use this extension, though. Please switch to some userland implementation.

**Comment by mlocati** [comment]
@cmb69  I'm not using it. I *simply* maintain [a script](https://github.com/mlocati/docker-php-extension-installer) that let people install PHP extensions in Docker containers very easily.

**Comment by mlocati** [comment]
> IMHO, no urgency until 8.1 API is final (so for RC)

@remicollet 8.1RC2 is available...

**Comment by llaville** [comment]
Now that 8.1.0RC3 is available, and after reading what we have on PECL extension homepage

![pecl_xmlrpc](https://user-images.githubusercontent.com/364342/136645261-e4a07e95-0117-43d1-ad3c-c8f5a7eb04f2.png)

@mlocati we should consider to let down support of xmlrpc for PHP 8.1 in docker-php-extension-installer
